spring:
  application:
    name: furniture

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/furniture
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379
